WITH EREKON AS (
    select
        rank() over(partition by EREKON.kd_brg || rpad(SUBSTR(EREKON.KD_LOKASI, 1, LENGTH(EREKON.KD_LOKASI)-5), 18, '0') 
        || substr(EREKON.kd_lokasi, LENGTH(EREKON.KD_LOKASI)-1,2) order by EREKON.TGL_BUKU) URUTAN,
        EREKON.kd_brg || rpad(SUBSTR(EREKON.KD_LOKASI, 1, LENGTH(EREKON.KD_LOKASI)-5), 18, '0') 
        || substr(EREKON.kd_lokasi, LENGTH(EREKON.KD_LOKASI)-1,2) BRGPER_X_SUBSATKER, 
        EREKON.KD_LOKASI AS KD_LOKASI,
        EREKON.KD_SSKEL AS KD_SSKEL, 
        EREKON.KD_BRG AS KD_BRG, 
        EREKON.KUANTITAS AS KUANTITAS, 
        EREKON.THNANG AS THNANG, 
        EREKON.RPH_ASET AS RPH_ASET, 
        EREKON.KDPERKBR AS KDPERKBR, 
        EREKON.JNS AS JNS, 
        EREKON.TGL_BUKU AS TGL_BUKU, 
        EREKON.KDBAES1 AS KDBAES1
    from erekon.t_sedia_data_21_211231_221202 EREKON
    where THNANG is not null
) , 
SAKTI_PERSEDIAAN AS (
    SELECT 
    PERD.BARANG_PERSEDIAAN AS PERD_BRG_PERSEDIAAN,
    case when 
        PERD.LAYER = 0 then 1
        else PERD.LAYER
    end AS PERD_LAYER,
    PERD.JUMLAH AS PERD_JUMLAH,
    PERD.HARGA_SATUAN AS PERD_HRGSAT,
    PERD.HARGA_SATUAN_TERHITUNG AS PERD_HRGSATTERHITUNG,
    PERD.HRG_PEMBANTU AS PERD_HRGPEMBANTU,
    PERD.KETERANGAN AS PERD_KETERANGAN,
    PERD.KODE_TRANSAKSI AS PERD_KDTRANSAKSI,
    PERH.JENIS_TRANSAKSI AS PERH_JENIS_TRANSAKSI,
    --header
    PERH.MTD_PNCTTN AS PERH_MTD_PNCTTN,
    PERH.NO_BUKTI AS PERH_NO_BUKTI,
    PERH.NO_DOKUMEN AS PERH_NO_DOKUMEN,
    PERH.ORGANISASI AS PERH_ORGANISASI,
    PERH.PERIODE_TUTUP_BUKU AS PERH_PERIODETUTUPBUKU,
    PERH.ASAL_BARANG AS PERH_ASAL_BARANG,
    PERH.HARGA_TOTAL AS PERH_HARGA_TOTAL,
    PERH.SATKER AS PERH_SATKER,
    PERH.STATUS AS PERH_STATUS,
    PERH.TAHUN_ANGGARAN AS PERH_TAHUN_ANGGARAN,
    PERH.TGL_DISETUJUI AS PERH_TGL_DISETUJUI,
    PERH.TGL_DOKUMEN AS PERH_TGL_DOKUMEN,
    PERH.TGL_PEMBUKUAN AS PERH_TGL_PEMBUKUAN,
    PERH.UAKPB AS PERH_UAKPB,
    PERH.UAKPB_LAINNYA AS PERH_UAKPBLAIN,
    PERH.PER_T_ADK AS PERH_PERT_ADK,
    PERH.UAKPB_INDUK AS PERH_UAKPB_INDUK,
    --DETAIL
    PERD.ERROR_CODE AS PERD_ERRORCODE,
    PERD.MTD_PNLN AS PERD_MTD_PNLN,
    PERD.SALDO_BARANG_INDUK AS PERD_SALDO_BRGINDUK,
    PERD.SALDO_BARANG_TERAKHIR AS PERD_SALDO_BRGTERAKHIR,
    PERD.SALDO_BRG_PEMBANTU AS PERD_SALDO_BRGPEMBANTU,
    PERD.STATUS_CALC AS PERD_STATUSCALC,
    PERD.TRANSAKSI_PERSEDIAAN AS PERD_TRANSPERSE_ID, 
    PERH.ID AS PERH_ID,
    PERH.PREV_ADK_ID AS PERH_PREVADK_ID,
    PERH.PREV_TRANS_ID AS PERH_PREVTRANS_ID,
    PERD.PREV_TRANS_ID AS PERD_PREV_TRANS_ID,
    PERD.ID AS PERD_ID
    FROM 
    (select * from saktiksl.bpk_per_t_trans_2021_221023 
        where JENIS_TRANSAKSI = 'M09') PERH
    LEFT JOIN 
    SAKTIKSL.bpk_per_t_trans_detail_2021_221023 PERD
    ON PERH.ID = PERD.TRANSAKSI_PERSEDIAAN
)
--- END WITH

SELECT distinct
    EREKON.URUTAN AS E_URUTAN,
    EREKON.BRGPER_X_SUBSATKER AS E_BRGPER_X_SUBSATKER, 
    EREKON.KD_LOKASI AS E_KDLOKASI,
    EREKON.KD_BRG AS E_KDBRG, 
    EREKON.THNANG AS E_THNANG, 
    EREKON.TGL_BUKU AS E_TGLBUKU, 
    EREKON.KUANTITAS AS E_KUANTITAS, 
    EREKON.RPH_ASET AS E_RPHASET, 
    PERD_BRG_PERSEDIAAN,
    PERD_LAYER,
    PERD_JUMLAH,
    PERD_HRGSAT,
    PERD_HRGSATTERHITUNG,
    PERD_HRGPEMBANTU,
    PERD_KETERANGAN,
    PERD_KDTRANSAKSI,
    PERH_JENIS_TRANSAKSI,
    --header
    PERH_MTD_PNCTTN,
    PERH_NO_BUKTI,
    PERH_NO_DOKUMEN,
    PERH_ORGANISASI,
    PERH_PERIODETUTUPBUKU,
    PERH_ASAL_BARANG,
    PERH_HARGA_TOTAL,
    PERH_SATKER,
    PERH_STATUS,
    PERH_TAHUN_ANGGARAN,
    PERH_TGL_DISETUJUI,
    PERH_TGL_DOKUMEN,
    PERH_TGL_PEMBUKUAN,
    PERH_UAKPB,
    PERH_UAKPBLAIN,
    PERH_PERT_ADK,
    PERH_UAKPB_INDUK,
    --DETAIL
    PERD_ERRORCODE,
    PERD_MTD_PNLN,
    PERD_SALDO_BRGINDUK,
    PERD_SALDO_BRGTERAKHIR,
    PERD_SALDO_BRGPEMBANTU,
    PERD_STATUSCALC,
    PERD_TRANSPERSE_ID, 
    PERH_ID,
    PERH_PREVADK_ID,
    PERH_PREVTRANS_ID,
    PERD_PREV_TRANS_ID,
    PERD_ID,
    --EREKON
    EREKON.KD_SSKEL AS E_KDSSKEL, 
    EREKON.KDPERKBR AS E_KDPERKBR, 
    EREKON.JNS AS E_JNS, 
    EREKON.KDBAES1 AS E_KDBAES1
from 
    EREKON 
FULL OUTER JOIN
    SAKTI_PERSEDIAAN PERS
    ON PERS.PERD_BRG_PERSEDIAAN = EREKON.BRGPER_X_SUBSATKER
    AND PERS.PERD_LAYER = EREKON.URUTAN
