DROP MATERIALIZED VIEW SAKTIKSL.MV_KOM_BAST_HIBAH_DETAIL_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_KOM_BAST_HIBAH_DETAIL_220930_221023
AS
SELECT	AA.ID_DOKUMEN_DETAIL,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'aktif'
				WHEN AA.DELETED = '1' THEN 'deleted'
			END AS UR_DELETED,
		AA.KODE_COA,
		substr(aa.KODE_COA,12,6)		kode_akun,
		ff.DESKRIPSI					NAMA_AKUN,
		AA.IS_DICATAT,
		CASE	WHEN AA.IS_DICATAT = '0' THEN 'Belum didetailkan'
				WHEN AA.IS_DICATAT = '1' THEN 'Sudah didetailkan'
			END AS UR_IS_DICATAT,
		AA.HARGA_SATUAN,
		AA.JUMLAH_BARANG,
		AA.KODE_BARANG,
		EE.DESKRIPSI					NAMA_BARANG,
		AA.KODE_BUKU_BESAR,
		substr(bb.kode_unit,1,3)		kode_ba_satker,
		trim(cc.deskripsi)				nama_ba_satker,
		substr(bb.kode_unit,-2)			kode_eselon1_satker,
		trim(dd.deskripsi)				nama_eselon1_satker,
		AA.SATKER_ID,
		trim(bb.deskripsi)				nama_satker,
		AA.SISA_HARGA,
		AA.SISA_JUMLAH,
		AA.TOTAL_HARGA,
		AA.ID_DOKUMEN
FROM	SAKTIKSL.BPK_KOM_BAST_HIBAH_DETAIL_220930_221023	AA
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 bb
	ON	aa.SATKER_ID = bb.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) cc
	ON	substr(bb.kode_unit,1,3) = cc.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) dd
	ON	bb.kode_unit = dd.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_KAT_SUBSUB_KELOMPOK_220731	EE
	ON	AA.KODE_BARANG = EE.KODE
left join	SAKTIKSL.BPK_ADM_R_AKUN_220731	ff
	ON	substr(aa.KODE_COA,12,6) = ff.KODE;
CREATE INDEX SAKTIKSL.IDX_MV_KBHDET_221023_BA ON SAKTIKSL.MV_KOM_BAST_HIBAH_DETAIL_220930_221023(kode_ba_satker);
CREATE INDEX SAKTIKSL.IDX_MV_KBHDET_221023_BAES1 ON SAKTIKSL.MV_KOM_BAST_HIBAH_DETAIL_220930_221023(kode_ba_satker||kode_eselon1_satker);