DROP MATERIALIZED VIEW SAKTIKSL.MV_AST_T_TRX_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_AST_T_TRX_220930_221023
AS 
with
ast_trx_all as
(	select	*
	from	saktiksl.BPK_AST_T_TRX_2021_221023
	union all
	select	*
	from	saktiksl.BPK_AST_T_TRX_220930_221023
)
SELECT	AA.ID,
		bb.ASSET_TRX_ID,
		AA.ASAL_PEROLEHAN,
		AA.DASAR_HARGA,
		case	when AA.DASAR_HARGA = '1' then 'Perolehan'
				when AA.DASAR_HARGA = '2' then 'Taksiran'
			end as ur_DASAR_HARGA,
		AA.FLAG_KIRIM,
		case	when AA.FLAG_KIRIM = '1' then 'Belum Dikirim'
				when AA.FLAG_KIRIM = '2' then 'Telah Dikirim'
			end as ur_FLAG_KIRIM,
		AA.HARGA_SATUAN,
		AA.HARGA_TOTAL,
		AA.ID_ASAL,
		AA.ID_BARANG_ASAL,
		AA.ID_KDP_TRX,
		AA.JENIS_DOKUMEN,
		case	when AA.JENIS_DOKUMEN = '1' then 'BAST Kontraktual'
				when AA.JENIS_DOKUMEN = '2' then 'Kwitansi'
				when AA.JENIS_DOKUMEN = '3' then 'BAST Non Kontraktual'
				when AA.JENIS_DOKUMEN = '11' then 'Transfer Melalui ADK'
				when AA.JENIS_DOKUMEN = '12' then 'Transfer Langsung'
				when AA.JENIS_DOKUMEN = '21' then 'Int Transfer per NUP'
				when AA.JENIS_DOKUMEN = '22' then 'Int Transfer per Kd Brg'
				when AA.JENIS_DOKUMEN = '23' then 'Int transfer semua brg'
				when AA.JENIS_DOKUMEN = '31' then 'RB/U/H'
				when AA.JENIS_DOKUMEN = '32' then 'Non RB/U/H'
				when AA.JENIS_DOKUMEN = '41' then 'Menambah MM'
				when AA.JENIS_DOKUMEN = '42' then 'Tidak Menambah MM'
			end as ur_JENIS_DOKUMEN,
		AA.JUMLAH,
		AA.KETERANGAN,
		AA.KODE_BARANG,
		DD.DESKRIPSI					nama_barang,
		AA.KODE_BAST_KUITANSI,
		AA.KODE_JENIS_TRANSAKSI,
		cc.DESKRIPSI					NAMA_TRANSAKSI,
		AA.KODE_KONDISI,
		case	when aa.KODE_KONDISI = '1' then 'Baik'
				when aa.KODE_KONDISI = '2' then 'Rusak Ringan'
				when aa.KODE_KONDISI = '3' then 'Rusak Berat'
			end as ur_KODE_KONDISI,
--		AA.KODE_SATKER,
		AA.KODE_UAKPB,
		SUBSTR(AA.KODE_UAKPB,1,3)		KODE_BA_SATKER,
		TRIM(GG.DESKRIPSI)				NAMA_BA_SATKER,
		SUBSTR(AA.KODE_UAKPB,4,2)		KODE_ESELON1_SATKER,
		TRIM(HH.DESKRIPSI)				NAMA_eselon1_SATKER,
		SUBSTR(AA.KODE_UAKPB,10,6)		KODE_SATKER_SATKER,
		TRIM(EE.DESKRIPSI)				NAMA_SATKER,
		SUBSTR(AA.KODE_UAKPB,16,3)		KODE_SUBSATKER_SATKER,
		SUBSTR(AA.KODE_UAKPB,1,5)||'.'||SUBSTR(AA.KODE_UAKPB,10,6)||'.'||SUBSTR(AA.KODE_UAKPB,16,3)
			||'.'||SUBSTR(AA.KODE_UAKPB,-2)||'.'||AA.KODE_BARANG
										kode_NUP,
		AA.KODEUAPKPB,
		SUBSTR(AA.KODEUAPKPB,1,3)		KODE_BA_TKTM,
		SUBSTR(AA.KODEUAPKPB,4,2)		KODE_ESELON1_TKTM,
		SUBSTR(AA.KODEUAPKPB,10,6)		KODE_SATKER_TKTM,
		SUBSTR(AA.KODEUAPKPB,16,3)		KODE_SUBSATKER_TKTM,
		CASE	WHEN AA.KODEUAPKPB IS NOT NULL THEN 
					SUBSTR(AA.KODEUAPKPB,1,5)||'.'||SUBSTR(AA.KODEUAPKPB,10,6)||'.'||SUBSTR(AA.KODEUAPKPB,16,3)
						||'.'||SUBSTR(AA.KODEUAPKPB,-2)||'.'||AA.KODE_BARANG
			END AS kode_NUP_TKTM,
		AA.KUANTITAS,
		AA.KUANTITAS_ASSET,
		AA.KUANTITAS_PERUBAHAN,
		AA.LOKASI_FISIK,
		AA.MASA_MANFAAT,
		AA.MASA_MANFAAT_LAMA,
		AA.MEREK_TIPE,
		AA.METODE,
--		AA.NAMA_SATKER,
		AA.NILAI_ASSET,
		AA.NILAI_PERUBAHAN,
		AA.NILAI_SATUAN,
		AA.NO_AKHIR,
		AA.NO_ASSET_AKHIR,
		AA.NO_AWAL,
		AA.NO_BAST_KUITANSI,
		AA.NO_BUKTI,
		AA.NO_DASAR_MUTASI,
		AA.NO_KONTRAK,
		AA.NO_SPPA,
		AA.STATUSADK,
		AA.STATUS_PERSETUJUAN,
		case	when AA.STATUS_PERSETUJUAN = '1' then 'Rekam'
				when AA.STATUS_PERSETUJUAN = '2' then 'Validasi'
				when AA.STATUS_PERSETUJUAN = '3' then 'Setuju'
			end as ur_STATUS_PERSETUJUAN,
		AA.STATUS_POSTING,
		AA.TAHUN_ANGGARAN,
		AA.TGL_BAST_KUITANSI,
		AA.TGL_DASAR_MUTASI,
		AA.TGL_PEMBUKUAN,
		AA.TGL_PEROLEHAN,
		AA.TOTAL_PRODUKSI,
		case	when AA.TOTAL_PRODUKSI = '99' then 'ubah tgl buku (kons)'
				when AA.TOTAL_PRODUKSI is null then 'Normal'
			end as UR_TOTAL_PRODUKSI,
		AA.TGL_AWAL_PEMAKAIAN,
		AA.PERIODE,
		AA.SISA_MASA_MANFAAT,
		AA.PROSENTASE_RENOVASI,
		AA.AKUM_PENYUSUTAN,
		AA.NILAI_ASSET_KOREKSI,
		AA.NILAI_BUKU,
		AA.NILAI_BUKU_KOREKSI,
		AA.SISA_MASA_MANFAAT_KOREKSI
from	ast_trx_all aa
left join
(	SELECT	distinct ASSET_TRX_ID
	from	saktiksl.BPK_AST_T_HISTORY_220930_221023
) bb
	on	AA.ID = bb.ASSET_TRX_ID
left join	saktiksl.BPK_ADM_R_JENIS_TRANSAKSI_220731 cc
	on	aa.KODE_JENIS_TRANSAKSI = cc.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_KAT_SUBSUB_KELOMPOK_220731	DD
	ON	AA.KODE_BARANG = DD.KODE
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 EE
	ON	SUBSTR(AA.KODE_UAKPB,10,6) = EE.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) GG
	ON	SUBSTR(AA.KODE_UAKPB,1,3) = GG.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) HH
	ON	SUBSTR(AA.KODE_UAKPB,1,3)||'.'||SUBSTR(AA.KODE_UAKPB,4,2) = HH.KODE;
create index saktiksl.IDX_ASTTRX_221023_BA on saktiksl.MV_AST_T_TRX_220930_221023 (KODE_BA_SATKER);
create index saktiksl.IDX_ASTTRX_221023_BAES1 on saktiksl.MV_AST_T_TRX_220930_221023 (KODE_BA_SATKER||KODE_ESELON1_SATKER);
create index saktiksl.IDX_ASTTRX_221023_ID on saktiksl.MV_AST_T_TRX_220930_221023 (ID);