drop materialized view saktiksl.MV_AST_T_TRX_KDP_220930_221023;
create materialized view saktiksl.MV_AST_T_TRX_KDP_220930_221023
AS 
with
TRX_KDP_ALL AS
(	SELECT	*
	FROM	SAKTIKSL.BPK_AST_T_TRX_KDP_2021_221023
	UNION ALL
	SELECT	*
	FROM	SAKTIKSL.BPK_AST_T_TRX_KDP_220930_221023
)
SELECT	AA.ID,
		AA.CARA_PEMBANGUNAN,
		AA.ID_ASAL,
		AA.JUMLAH,
		AA.KETERANGAN,
		AA.KODE_BARANG,
		BB.DESKRIPSI					NAMA_BARANG,
		AA.KODE_BAST,
		AA.KODE_JENIS_TRANSAKSI,
		CC.DESKRIPSI					NAMA_TRANSAKSI,
		AA.KODE_KONDISI,
		CASE	WHEN AA.KODE_KONDISI = '1' THEN 'Baik'
				WHEN AA.KODE_KONDISI = '2' THEN 'rusak Ringan'
				WHEN AA.KODE_KONDISI = '3' THEN 'Rusak Berat'
			END AS UR_KONDISI,
		AA.KODE_MATA_UANG,
--		AA.KODE_SATKER,
		AA.KODE_UAKPB,
		SUBSTR(AA.KODE_UAKPB,1,3)		KODE_BA_SATKER,
		TRIM(GG.DESKRIPSI)				NAMA_BA_SATKER,
		SUBSTR(AA.KODE_UAKPB,4,2)		KODE_eselon1_SATKER,
		TRIM(HH.DESKRIPSI)				NAMA_eselon1_SATKER,
		SUBSTR(AA.KODE_UAKPB,10,6)		kode_satker,
		TRIM(DD.DESKRIPSI)				NAMA_SATKER,
		SUBSTR(AA.KODE_UAKPB,16,3)		kode_sub_satker,
		AA.LOKASI_KDP,
		AA.NAMA_KONTRAKTOR,
--		AA.NAMA_SATKER,
		AA.NILAI_ASSET_KDP,
		AA.NILAI_KONTRAK,
		AA.NILAI_VALAS,
		AA.NO_AKHIR,
		AA.NO_ASSET_AKHIR,
		AA.NO_AWAL,
		AA.NO_BAST,
		AA.NO_KONTRAK,
		AA.NO_SPPA,
		AA.NO_SURAT_KEPUTUSAN,
		AA.PROSENTASE_PENGERJAAN,
		AA.STATUS_PERSETUJUAN,
		CASE	WHEN AA.STATUS_PERSETUJUAN = '1' THEN 'Rekam'
				WHEN AA.STATUS_PERSETUJUAN = '2' THEN 'Validasi'
				WHEN AA.STATUS_PERSETUJUAN = '3' THEN 'Setuju'
			END AS UR_STATUS_PERSETUJUAN,
		AA.STATUS_POSTING,
		AA.TAHUN_ANGGARAN,
		AA.TGL_AKHIR_KONTRAK,
		AA.TGL_AWAL_KONTRAK,
		AA.TGL_BAST,
		AA.TGL_PEMBUKUAN,
		AA.TGL_PEROLEHAN,
		AA.TGL_SURAT_KEPUTUSAN,
		AA.PERIODE,
		AA.KODEUAPKPB,
		AA.JENIS_DOKUMEN,
		AA.STATUS_ADK,
		ee.AKUN,
		ee.NAMA_AKUN,
		SUBSTR(AA.KODE_UAKPB,1,5)||'.'||SUBSTR(AA.KODE_UAKPB,10,6)||'.'||SUBSTR(AA.KODE_UAKPB,16,3)
				||'.'||SUBSTR(AA.KODE_UAKPB,-2)||'.'||AA.KODE_BARANG
										kode_NUP
FROM	TRX_KDP_ALL	AA
LEFT JOIN	SAKTIKSL.BPK_ADM_R_KAT_SUBSUB_KELOMPOK_220731	BB
	ON	AA.KODE_BARANG = BB.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_JENIS_TRANSAKSI_220731	CC
	ON	AA.KODE_JENIS_TRANSAKSI = cc.KODE
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 DD
	ON	SUBSTR(AA.KODE_UAKPB,10,6) = DD.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) GG
	ON	SUBSTR(AA.KODE_UAKPB,1,3) = GG.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) HH
	ON	SUBSTR(AA.KODE_UAKPB,1,3)||'.'||SUBSTR(AA.KODE_UAKPB,4,2) = HH.KODE
LEFT JOIN	saktiksl.REF_ASET_BARANG_MONSAKTI_2022 ee
	ON	aa.KODE_BARANG = ee.KODE_BARANG
;
create index saktiksl.IDX_MV_ATTK_221023_BA on saktiksl.MV_AST_T_TRX_KDP_220930_221023(KODE_BA_SATKER);
create index saktiksl.IDX_MV_ATTK_221023_BAES1 on saktiksl.MV_AST_T_TRX_KDP_220930_221023(KODE_BA_SATKER||KODE_eselon1_SATKER);
create index saktiksl.IDX_MV_ATTK_221023_ID on saktiksl.MV_AST_T_TRX_KDP_220930_221023(ID);