drop materialized view saktiksl.MV_PER_T_TRANS_DETAIL_220930_221023;
create materialized view saktiksl.MV_PER_T_TRANS_DETAIL_220930_221023
as
WITH
NILAI_TRANS AS
(	SELECT	KODE_AKUN,
			NAMA_AKUN,
			KODE_COA,
			TRANS_PER_DETAIL,
			SUM(NILAI_DEBET)					NILAI_TRANS_DEBET,
			-SUM(NILAI_KREDIT)					NILAI_TRANS_KREDIT,
			SUM(NILAI_DEBET)-SUM(NILAI_KREDIT)	NILAI_TRANS
	FROM	SAKTIKSL.MV_PER_T_JURNAL_220930_221023
	GROUP BY	KODE_AKUN,
				NAMA_AKUN,
				KODE_COA,
				TRANS_PER_DETAIL
),
TRANS_DETAIL_ALL AS
(	SELECT	AA1.*,
			SUBSTR(BARANG_PERSEDIAAN,-20) KD_LOKASI,
			SUBSTR(BARANG_PERSEDIAAN,1,(LENGTH(BARANG_PERSEDIAAN)-20)) KD_BRG
	FROM	SAKTIKSL.BPK_PER_T_TRANS_DETAIL_2021_221023	AA1
	union all
	SELECT	AA1.*,
			SUBSTR(BARANG_PERSEDIAAN,-20) KD_LOKASI,
			SUBSTR(BARANG_PERSEDIAAN,1,(LENGTH(BARANG_PERSEDIAAN)-20)) KD_BRG
	FROM	SAKTIKSL.BPK_PER_T_TRANS_DETAIL_220930_221023	AA1
)
select	AA.ID,
		AA.ERROR_CODE,
		AA.HARGA_SATUAN,
		AA.HARGA_SATUAN_TERHITUNG,
		AA.JUMLAH,
		AA.KETERANGAN,
		AA.KODE_TRANSAKSI,
		CASE	WHEN AA.KODE_TRANSAKSI = -1 THEN 'Transaksi Keluar'
				WHEN AA.KODE_TRANSAKSI = 1 THEN 'Transaksi Masuk'
			END AS UR_KODE_TRANSAKSI,
		AA.LAYER,
		AA.MTD_PNLN,
		AA.PREV_TRANS_ID,
		AA.SALDO_BARANG_TERAKHIR,
		AA.STATUS_CALC,
		AA.BARANG_PERSEDIAAN,
		SUBSTR(AA.KD_LOKASI,1,3)				KODE_BA_SATKER,
		trim(DD.deskripsi)						nama_ba_satker,
		SUBSTR(AA.KD_LOKASI,4,2)				KODE_ESELON1_SATKER,
		trim(EE.deskripsi)						nama_eselon1_satker,
		SUBSTR(AA.KD_LOKASI,10,6)				KODE_SATKER,
		trim(CC.deskripsi)						nama_satker,
		SUBSTR(AA.KD_LOKASI,16,3)				KODE_SUBSATKER,
		SUBSTR(AA.KD_BRG,1,10)					KODE_BARANG,
		TRIM(FF.DESKRIPSI)						NAMA_BARANG,
		TR.KODE_AKUN,
		TR.NAMA_AKUN,
		TR.KODE_COA,
--		GG.AKUN									KODE_AKUN,
--		GG.NAMA_AKUN							NAMA_AKUN,
		SUBSTR(AA.KD_BRG,11,LENGTH(KD_BRG))		NO_BARANG,
		SUBSTR(AA.KD_LOKASI,1,5)||'.'||SUBSTR(AA.KD_LOKASI,10,6)||'.'||SUBSTR(AA.KD_LOKASI,16,3)
			||'.'||SUBSTR(AA.KD_LOKASI,-2)||'.'||SUBSTR(AA.KD_BRG,1,10)||'.'||SUBSTR(AA.KD_BRG,11,LENGTH(KD_BRG))	
												KODE_NUP,
		AA.SALDO_BRG_PEMBANTU,
		AA.HRG_PEMBANTU,
		AA.SALDO_BARANG_INDUK,
		case	when aa.KODE_TRANSAKSI = 1 then AA.JUMLAH
				when aa.KODE_TRANSAKSI = -1 then -AA.JUMLAH
			end as KUANTITAS_TRANSAKSI,
		TR.NILAI_TRANS_DEBET,
		TR.NILAI_TRANS_KREDIT,
		TR.NILAI_TRANS,
--		case	WHEN HH.JENIS_TRANSAKSI IN ('K99','M99') THEN 0
--				when aa.KODE_TRANSAKSI = 1 then (AA.JUMLAH * AA.HARGA_SATUAN_TERHITUNG)
--				when aa.KODE_TRANSAKSI = -1 then -(AA.JUMLAH * AA.HARGA_SATUAN_TERHITUNG)
--			end as NILAI_TRANSAKSI,
--		case	WHEN HH.JENIS_TRANSAKSI IN ('K99','M99') THEN 0
--				when aa.KODE_TRANSAKSI = 1 then (AA.JUMLAH * AA.HARGA_SATUAN)
--				when aa.KODE_TRANSAKSI = -1 then -(AA.JUMLAH * AA.HARGA_SATUAN)
--			end as NILAI_TRANSAKSI2,
		AA.TRANSAKSI_PERSEDIAAN,
		hh.DOK_ASAL,
		HH.ID_DOK_ASAL,
		HH.JENIS_TRANSAKSI,
		HH.NAMA_TRANSAKSI,
		HH.NO_BUKTI,
		HH.NO_DOKUMEN,
		HH.PERIODE_TUTUP_BUKU,
		HH.STATUS,
		HH.UR_STATUS,
		HH.UAKPB,
		HH.KODE_NUP||'.'||SUBSTR(AA.KD_BRG,1,10)||'.'||SUBSTR(AA.KD_BRG,11,LENGTH(KD_BRG))
												KODE_NUP_TRANS,
		HH.UAKPB_LAINNYA,
		HH.KODE_BA_SATKER_LAINNYA,
		HH.NAMA_BA_SATKER_LAINNYA,
		HH.KODE_ESELON1_SATKER_LAINNYA,
		HH.NAMA_ESELON1_SATKER_LAINNYA,
		HH.KODE_SATKER_LAINNYA,
		HH.NAMA_SATKER_LAINNYA,
		HH.KODE_SUBSATKER_LAINNYA,
		HH.KODE_NUP_LAINNYA,
		HH.UAKPB_INDUK,
		HH.TGL_DISETUJUI,
		HH.TGL_DOKUMEN,
		HH.TGL_PEMBUKUAN
FROM	TRANS_DETAIL_ALL	AA
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 CC
	ON	SUBSTR(AA.KD_LOKASI,10,6) = CC.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) DD
	ON	SUBSTR(AA.KD_LOKASI,1,3) = DD.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) EE
	ON	SUBSTR(AA.KD_LOKASI,1,3)||'.'||SUBSTR(AA.KD_LOKASI,4,2) = EE.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_KAT_SUBSUB_KELOMPOK_220731	FF
	ON	SUBSTR(AA.KD_BRG,1,10) = FF.KODE
LEFT JOIN	SAKTIKSL.REF_ASET_BARANG_MONSAKTI_2022	GG
	ON	SUBSTR(AA.KD_BRG,1,10) = GG.KODE_BARANG
left join	saktiksl.MV_PER_T_TRANS_220930_221023	hh
	on	aa.TRANSAKSI_PERSEDIAAN = hh.id
LEFT JOIN	NILAI_TRANS	TR
	ON	AA.ID = TR.TRANS_PER_DETAIL;;
create index saktiksl.MV_PTTRND_221023_BA on saktiksl.MV_PER_T_TRANS_DETAIL_220930_221023 (kode_ba_satker);
create index saktiksl.MV_PTTRND_221023_BAES1 on saktiksl.MV_PER_T_TRANS_DETAIL_220930_221023 (kode_ba_satker||kode_eselon1_satker);
create index saktiksl.MV_PTTRND_221023_NUP1 on saktiksl.MV_PER_T_TRANS_DETAIL_220930_221023 (KODE_NUP_TRANS);
create index saktiksl.MV_PTTRND_221023_NUP2 on saktiksl.MV_PER_T_TRANS_DETAIL_220930_221023 (KODE_NUP_LAINNYA);