DROP MATERIALIZED VIEW SAKTIKSL.MV_CT_UANG_MASUK_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_CT_UANG_MASUK_220930_221023
--Tabel mencatat kas masuk
AS
select	AA.KODE_AKUN,
		BB.DESKRIPSI					NAMA_AKUN,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'data aktif'
				WHEN AA.DELETED = '1' THEN 'data dihapus'
			END AS UR_DELETED,
		AA.JENIS_PEM_KAS,
		CASE	WHEN AA.JENIS_PEM_KAS = '1' THEN 'kas tunai'
				WHEN AA.JENIS_PEM_KAS = '2' THEN 'kas bank'
				WHEN AA.JENIS_PEM_KAS = '3' THEN 'non SBS'
			END AS UR_JENIS_PEM_KAS,
		AA.JUMLAH,
		AA.KETERANGAN,
		AA.KODE_KPPN,
		TRIM(CC.NMKPPN)					NAMA_KPPN,
		AA.KODE_PROGRAM,
		TRIM(DD.NMPROGRAM)				NAMA_PROGRAM,
		AA.KODE_KEGIATAN,
		TRIM(EE.NMGIAT)					NAMA_KEGIATAN,
		AA.KODE_OUTPUT,
		TRIM(FF.NMOUTPUT)				NAMA_OUTPUT,
		AA.KODE_LOKASI,
		TRIM(JJ.DESKRIPSI)				NAMA_LOKASI,
		AA.KODE_NO_DIPA,
		AA.NO_REF_GL,
		AA.NO_SBS,
		AA.NO_SPN,
		SUBSTR(AA.KODE_PROGRAM,1,3)		KODE_BA_SATKER,
		TRIM(KK.DESKRIPSI)				NAMA_BA_SATKER,
		SUBSTR(AA.KODE_PROGRAM,5,2)		KODE_ESELON1_SATKER,
		TRIM(LL.DESKRIPSI)				NAMA_ESELON1_SATKER,
		AA.KODE_SATKER,
		TRIM(MM.DESKRIPSI)				NAMA_SATKER,
		AA.STATUS,
		CASE	WHEN AA.STATUS = '0' THEN 'belum di setor'
				WHEN AA.STATUS = '1' THEN 'sudah di setor'
			END AS UR_STATUS,
		AA.KODE_TAHUN_ANGGARAN,
		AA.TGL_SBS,
		AA.TGL_SPN,
		AA.NO_SSBP,
		AA.JENIS_PNBP,
		CASE	WHEN AA.JENIS_PNBP = '4' THEN 'PNBP fungsional'
				WHEN AA.JENIS_PNBP = '11' THEN 'pemindahbukuan BLU'
				WHEN AA.JENIS_PNBP = '7' THEN 'PNBP umum'
			END AS UR_JENIS_PNBP,
		AA.FLAG_HIBAH,
		CASE	WHEN AA.FLAG_HIBAH = '0' THEN 'bukan hibah'
				WHEN AA.FLAG_HIBAH = '1' THEN 'hibah'
			END AS UR_FLAG_HIBAH,
		AA.FLAG_OWNER,
		CASE	WHEN AA.FLAG_OWNER = '1' THEN 'bendahara pengeluaran'
				WHEN AA.FLAG_OWNER = '0' THEN 'bendahara penerimaan'
			END AS UR_FLAG_OWNER,
		AA.NO_REGISTER,
		AA.NO_SPP,
		AA.NILAI_PENGESAHAN,
		AA.FLAG_MIG,
		AA.MATCHING_PIUTANG,
		AA.SALDO_PIUTANG,
		AA.TAHUN_ANGGARAN_HIBAH,
		AA.KODE_UNIT_TEKNIS,
		AA.KODE_SATKER_INTRACO,
		TRIM(NN.DESKRIPSI)				NAMA__SATKER_INTRACO,
		AA.KODE_SUMBER_DANA,
		OO.DESKRIPSI					NAMA_SUMBER_DANA
from	saktiksl.BPK_CT_UANG_MASUK_220930_221023	AA
LEFT JOIN	SAKTIKSL.BPK_ADM_R_AKUN_220731	BB
	ON	AA.KODE_AKUN = BB.KODE
LEFT JOIN	EREKON.T_KPPN_220525	CC
	ON	AA.KODE_KPPN = CC.KDKPPN
LEFT JOIN	SAKTIKSL.T_PROGRAM_220912	DD
	ON	AA.KODE_PROGRAM = DD.KDDEPT||'.'||DD.KDUNIT||'.'||DD.KDPROGRAM
LEFT JOIN	SAKTIKSL.T_GIAT_220912	EE
	ON	AA.KODE_KEGIATAN = EE.KDDEPT||'.'||EE.KDUNIT||'.'||EE.KDPROGRAM||'.'||EE.KDGIAT
LEFT JOIN	SAKTIKSL.T_OUTPUT_220912	FF
	ON	AA.KODE_KEGIATAN||'.'||AA.KODE_OUTPUT = FF.KDDEPT||'.'||FF.KDUNIT||'.'||FF.KDPROGRAM||'.'||FF.KDGIAT||'.'||FF.KDOUTPUT
LEFT JOIN
	(	SELECT	*
		FROM	SAKTIKSL.BPK_ADM_R_LOKASI_220731
		WHERE	LEVEL_ = '3'
	) JJ
	ON	AA.KODE_LOKASI = JJ.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) KK
	ON	SUBSTR(AA.KODE_PROGRAM,1,3) = KK.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) LL
	ON	SUBSTR(AA.KODE_PROGRAM,1,6) = LL.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_SATKER_220731	MM
	ON	AA.KODE_SATKER = MM.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_SATKER_220731	NN
	ON	AA.KODE_SATKER_INTRACO = NN.KODE
LEFT JOIN	SAKTIKSL.REF_SUMBER_DANA_2022	OO
		ON	AA.KODE_SUMBER_DANA = OO.KODE;
CREATE INDEX SAKTIKSL.MV_CTUM_221023_BA ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(KODE_BA_SATKER);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_BAES1 ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(KODE_BA_SATKER||kode_eselon1_satker);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_AKUN ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(KODE_AKUN);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_DEL ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(DELETED);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_REF ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(NO_REF_GL);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_SBS ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(NO_SBS);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_SPN ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(NO_SPN);
CREATE INDEX SAKTIKSL.MV_CTUM_221023_SSBP ON SAKTIKSL.MV_CT_UANG_MASUK_220930_221023(NO_SSBP);