DROP MATERIALIZED VIEW SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023
--Tabel mencatat transaksi pengembalian belanja
AS
SELECT	AA.CARA_BAYAR,
		CASE	WHEN AA.CARA_BAYAR = '1' THEN 'tunai'
				WHEN AA.CARA_BAYAR = '2' THEN 'non tunai'
			END AS UR_CARA_BAYAR,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'data aktif'
				WHEN AA.DELETED = '1' THEN 'data dihapus'
			END AS UR_DELETED,
		AA.JUMLAH,
		AA.KETERANGAN,
		AA.NO_PEMBAYARAN,
		AA.NO_REF_GL,
		SUBSTR(BB.KODE_UNIT,1,3)	KODE_BA_SATKER,
		trim(cc.deskripsi)			NAMA_BA_SATKER,
		SUBSTR(BB.KODE_UNIT,-2)		KODE_ESELON1_SATKER,
		TRIM(DD.DESKRIPSI)			NAMA_ESELON1_SATKER,
		AA.KODE_SATKER,
		TRIM(BB.DESKRIPSI)			NAMA_SATKER,
		AA.NO_SP2D,
		AA.KODE_TAHUN_ANGGARAN,
		AA.TGL_PEMBAYARAN,
		AA.KODE_UNIT_TEKNIS,
		AA.STATUS_TUNAI
FROM	SAKTIKSL.BPK_BEN_DANA_TITIP_220930_221023	AA
LEFT JOIN	SAKTIKSL.BPK_ADM_R_SATKER_220731	BB
	ON	AA.KODE_SATKER = BB.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) cc
	ON	SUBSTR(BB.KODE_UNIT,1,3) = cc.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) dd
	ON	BB.KODE_UNIT = DD.KODE;
CREATE INDEX SAKTIKSL.IDX_MVBDT221023_BA ON SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023(KODE_BA_SATKER);
CREATE INDEX SAKTIKSL.IDX_MVBDT221023_BAES1 ON SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023(KODE_BA_SATKER||KODE_ESELON1_SATKER);
CREATE INDEX SAKTIKSL.IDX_MVBDT221023_PEMB ON SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023(NO_PEMBAYARAN);
CREATE INDEX SAKTIKSL.IDX_MVBDT221023_REF ON SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023(NO_REF_GL);
CREATE INDEX SAKTIKSL.IDX_MVBDT221023_SP2D ON SAKTIKSL.MV_BEN_DANA_TITIP_220930_221023(NO_SP2D);