DROP MATERIALIZED VIEW SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023
--Tabel mencatat transaksi pengembalian belanja
AS
SELECT	AA.KODE_AKUN,
		LL.DESKRIPSI				NAMA_AKUN,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'data aktif'
				WHEN AA.DELETED = '1' THEN 'data dihapus'
			END AS UR_DELETED,
		AA.KODE_BANK,
		AA.CABANG,
		AA.JUMLAH,
		AA.KODE_KEMENTRIAN,
		trim(cc.deskripsi)			NAMA_KEMENTERIAN,	
		SUBSTR(KODE_KEGIATAN,5,2)	KODE_ESELON1,
		TRIM(DD.DESKRIPSI)			NAMA_ESELON1,
		AA.KODE_SATKER,
		TRIM(BB.DESKRIPSI)			NAMA_SATKER,
		AA.KODE_SUB_FUNGSI,
		EE.NM_SUBFUNGSI				NAMA_SUBFUNGSI,
		AA.KODE_PROGRAM,
		TRIM(FF.NMPROGRAM)			NAMA_PROGRAM,
		AA.KODE_KEGIATAN,
		TRIM(GG.NMGIAT)				NAMA_KEGIATAN,
		AA.KODE_OUTPUT,
		TRIM(HH.NMOUTPUT)			NAMA_OUTPUT,
		AA.KETERANGAN,
		AA.KODE_KPPN,
		TRIM(II.NMKPPN)				NAMA_KPPN,
		AA.KODE_LOKASI,
		TRIM(JJ.DESKRIPSI)			NAMA_LOKASI,
		AA.KODE_NO_DIPA,
		AA.NO_REF_GL,										--Terisi jika mengurangi kas lainnya di bendahara pengeluaran
		AA.NO_REF_GL2,										--Terisi kode buku besar pengembalian belanja
		AA.NO_SSPB,
		AA.NO_NTPN,
		AA.STATUS,
		CASE	WHEN AA.STATUS = '0' THEN 'Belum dibuat SPP Pengembalian'
				WHEN AA.STATUS = '1' THEN 'Sudah dibuat SPP Pengembalian'
			END AS UR_STATUS,
		AA.KODE_TAHUN_ANGGARAN,
		AA.TGL_SSPB,
		AA.TGL_TERIMA_BANK,
		AA.NO_REF_GL_KOROLARI,
		AA.KODE_UNIT_TEKNIS,
		AA.NTB,												--Nomor Transaksi Bank dari MPN
		AA.CARA_SETOR,
		CASE	WHEN AA.CARA_SETOR = '1' THEN 'kas tunai'
				WHEN AA.CARA_SETOR = '2' THEN 'kas bank'
			END AS UR_CARA_SETOR,
		AA.KODE_SUMBER_DANA,
		TRIM(KK.DESKRIPSI)					NAMA_SUMBER_DANA
FROM	SAKTIKSL.BPK_BEN_KEMBALI_BELANJA_220930_221023	AA
LEFT JOIN	SAKTIKSL.BPK_ADM_R_SATKER_220731	BB
	ON	AA.KODE_SATKER = BB.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) cc
	ON	AA.KODE_KEMENTRIAN = cc.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) dd
	ON	SUBSTR(KODE_KEGIATAN,1,6) = DD.KODE
LEFT JOIN
	(	SELECT	DISTINCT KD_SUBFUNGSI,
				trim(NM_SUBFUNGSI) NM_SUBFUNGSI
		FROM	EREKON.T_SUBFUNGSI_span_310820
	) EE
	ON	AA.KODE_SUB_FUNGSI = SUBSTR(EE.KD_SUBFUNGSI,1,2)||'.'||SUBSTR(EE.KD_SUBFUNGSI,-2)
LEFT JOIN	SAKTIKSL.T_PROGRAM_220912	FF
	ON	AA.KODE_PROGRAM = FF.KDDEPT||'.'||FF.KDUNIT||'.'||FF.KDPROGRAM
LEFT JOIN	SAKTIKSL.T_GIAT_220912	GG
	ON	AA.KODE_KEGIATAN = GG.KDDEPT||'.'||GG.KDUNIT||'.'||GG.KDPROGRAM||'.'||GG.KDGIAT
LEFT JOIN	SAKTIKSL.T_OUTPUT_220912	HH
	ON	AA.KODE_OUTPUT = HH.KDDEPT||'.'||HH.KDUNIT||'.'||HH.KDPROGRAM||'.'||HH.KDGIAT||'.'||HH.KDOUTPUT
LEFT JOIN	EREKON.T_KPPN_220525	II
	ON	AA.KODE_KPPN = II.KDKPPN
LEFT JOIN
	(	SELECT	*
		FROM	SAKTIKSL.BPK_ADM_R_LOKASI_220731
		WHERE	LEVEL_ = '3'
	) JJ
	ON	AA.KODE_LOKASI = JJ.KODE
LEFT JOIN	SAKTIKSL.REF_SUMBER_DANA_2022	KK
	ON	AA.KODE_SUMBER_DANA = KK.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_AKUN_220731	LL
	ON	AA.KODE_AKUN = LL.KODE;
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_BA ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(KODE_KEMENTRIAN);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_BAES1 ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(KODE_KEMENTRIAN||KODE_ESELON1);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_AKUN ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(KODE_AKUN);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_DEL ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(DELETED);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_REF ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(NO_REF_GL);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_REF2 ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(NO_REF_GL2);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_SSPB ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(NO_SSPB);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_NTPN ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(NO_NTPN);
CREATE INDEX SAKTIKSL.IDX_MVBKB_221023_NTB ON SAKTIKSL.MV_BEN_KEMBALI_BELANJA_220930_221023(NO_NTB);