DROP MATERIALIZED VIEW SAKTIKSL.MV_BEN_SETORAN_UP_TUP_PNBP_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_BEN_SETORAN_UP_TUP_PNBP_220930_221023
--Tabel mencatat setoran pajak bendahara penerimaan
AS
SELECT	AA.NTPN,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'data aktif'
				WHEN AA.DELETED = '1' THEN 'data dihapus'
			END AS UR_DELETED,
		AA.KODE_AKUN,
		trim(bb.DESKRIPSI)					NAMA_AKUN,
		AA.CARA_SETOR,
		CASE	WHEN AA.CARA_SETOR = '1' THEN 'tunai'
				WHEN AA.CARA_SETOR = '2' THEN 'non tunai'
			END AS UR_CARA_SETOR,
		AA.JENIS_PENGEMBALIAN,
		case	when AA.JENIS_PENGEMBALIAN in ('1','9') then 'UP'
				when AA.JENIS_PENGEMBALIAN in ('2','10') then 'TUP'
				when AA.JENIS_PENGEMBALIAN = '8' then 'surplus BLU'
				when AA.JENIS_PENGEMBALIAN = '12' then 'dana hibah'
				when AA.JENIS_PENGEMBALIAN IN ('3','4','5','7') THEN 'PNBP'
			END AS UR_JENIS_PENGEMBALIAN,
		AA.JENIS_PUNGUT,
		AA.JUMLAH,
		AA.KODE_KEMENTRIAN,
		TRIM(CC.DESKRIPSI)					NAMA_KEMENTRIAN,
		substr(AA.KODE_PROGRAM,5,2)			kode_eselon1,
		TRIM(DD.DESKRIPSI)					NAMA_eselon1,
		AA.KODE_SATKER,
		TRIM(EE.DESKRIPSI)					NAMA_satker,
		AA.KODE_SUB_FUNGSI,
		AA.KODE_PROGRAM,
		TRIM(GG.NMPROGRAM)					NAMA_PROGRAM,
		AA.KODE_KEGIATAN,
		TRIM(HH.NMGIAT)						NAMA_KEGIATAN,
		AA.KODE_OUTPUT,
		TRIM(II.NMOUTPUT)					NAMA_OUTPUT,
		AA.KETERANGAN,
		AA.KODE_KPPN,
		TRIM(JJ.NMKPPN)						NAMA_KPPN,
		AA.KODE_LOKASI,
		TRIM(KK.DESKRIPSI)					NAMA_LOKASI,
		AA.KODE_NO_DIPA,
		AA.NO_REF_GL,
		AA.NO_SPN,
		AA.NO_SSBP,
		AA.STATUS,
		AA.KODE_TAHUN_ANGGARAN,
		AA.TGL_SPN,
		AA.TGL_SSBP,
		AA.TGL_TERIMA_BANK,
		AA.TGL_DIPA,
		AA.FLAG_OWNER,
		CASE	WHEN AA.FLAG_OWNER = '0' THEN 'bendahara penerimaan'
				WHEN AA.FLAG_OWNER = '1' then 'bendahara pengeluaran'
			end as ur_FLAG_OWNER,
		AA.NO_REF_GL_KOROLARI,
		AA.KODE_UNIT_TEKNIS,
		AA.MATCHING_PIUTANG,
		AA.SALDO_PIUTANG,
		AA.NTB,
		AA.KURS,
		AA.NILAI_VALAS,
		AA.MATA_UANG,
		AA.KODE_SUMBER_DANA
FROM	SAKTIKSL.BPK_BEN_SETORAN_UP_TUP_PNBP_220930_221023	AA
LEFT JOIN	SAKTIKSL.BPK_ADM_R_AKUN_220731	BB
	ON	AA.KODE_AKUN = BB.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) CC
	ON	AA.KODE_KEMENTRIAN = CC.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) DD
	ON	SUBSTR(AA.KODE_PROGRAM,1,6) = DD.KODE
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 EE
	ON	aa.KODE_SATKER = EE.KODE
LEFT JOIN	SAKTIKSL.T_PROGRAM_220912	GG
	ON	AA.KODE_PROGRAM = GG.KDDEPT||'.'||GG.KDUNIT||'.'||GG.KDPROGRAM
LEFT JOIN	SAKTIKSL.T_GIAT_220912	HH
	ON	AA.KODE_KEGIATAN = HH.KDDEPT||'.'||HH.KDUNIT||'.'||HH.KDPROGRAM||'.'||HH.KDGIAT
LEFT JOIN	SAKTIKSL.T_OUTPUT_220912	II
	ON	AA.KODE_OUTPUT = II.KDDEPT||'.'||II.KDUNIT||'.'||II.KDPROGRAM||'.'||II.KDGIAT||'.'||II.KDOUTPUT
LEFT JOIN	EREKON.T_KPPN_220525	JJ
	ON	AA.KODE_KPPN = JJ.KDKPPN
LEFT JOIN
	(	SELECT	*
		FROM	SAKTIKSL.BPK_ADM_R_LOKASI_220731
		WHERE	LEVEL_ = '3'
	) KK
	ON	AA.KODE_LOKASI = KK.KODE;
CREATE INDEX SAKTIKSL.IDX_MV_BSTP_221023_BA ON SAKTIKSL.MV_BEN_SETORAN_UP_TUP_PNBP_220930_221023 (KODE_KEMENTRIAN);
CREATE INDEX SAKTIKSL.IDX_MV_BSTP_221023_BAES1 ON SAKTIKSL.MV_BEN_SETORAN_UP_TUP_PNBP_220930_221023 (KODE_KEMENTRIAN||kode_eselon1);