DROP MATERIALIZED VIEW SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023
AS
--Tabel mencatat transaksi kas bank di bendahara penerimaan
SELECT	AA.BUKTI_PEMINDAHAN,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'data aktif'
				WHEN AA.DELETED = '1' THEN 'data dihapus'
			END AS UR_DELETED,
		AA.JNS_AKTIFITAS,
		CASE	WHEN AA.JNS_AKTIFITAS = '0' THEN 'SBS'
				WHEN AA.JNS_AKTIFITAS = '1' THEN 'SETOR_KE_BANK'
				WHEN AA.JNS_AKTIFITAS = '2' THEN 'TARIK_DARI_BANK'
				WHEN AA.JNS_AKTIFITAS = '3' THEN 'SETOR_MASUK_NON_TUNAI'
				WHEN AA.JNS_AKTIFITAS = '5' THEN 'MIGRASI_DATA'
				WHEN AA.JNS_AKTIFITAS = '8' THEN 'PINDAH_KAS_BANK_KETUNAI'
				WHEN AA.JNS_AKTIFITAS = '9' THEN 'PINDAH_KAS_TUNAI_KEBANK'
			END AS UR_JNS_AKTIFITAS,
		AA.JUMLAH,
		AA.NO_REFERENSI,
		substr(bb.kode_unit,1,3)		kode_ba_satker,
		trim(cc.deskripsi)				nama_ba_satker,
		substr(bb.kode_unit,-2)			kode_eselon1_satker,
		trim(dd.deskripsi)				nama_eselon1_satker,
		AA.KODE_SATKER,
		trim(bb.deskripsi)				nama_satker,
		AA.KODE_TAHUN_ANGGARAN,
		AA.TGL_TRANSAKSI,
		AA.URAIAN,
		AA.PIHAK_KETIGA,
		AA.NO_REF_GL,
		AA.KATEGORI_KAS,
		CASE	WHEN AA.KATEGORI_KAS = '111' THEN 'SBS_BEN_PEN'
				WHEN AA.KATEGORI_KAS = '155' THEN 'KAS_PNBP'
				WHEN AA.KATEGORI_KAS = '333' THEN 'PAJAK_BEN_PEN'
				WHEN AA.KATEGORI_KAS = '444' THEN 'KAS_LAIN_BEN_PEN'
				WHEN AA.KATEGORI_KAS = '222' THEN 'KAS DPK'
			END AS UR_KATEGORI_KAS
FROM	saktiksl.BPK_KAS_BANK_BEN_PEN_220930_221023	aa
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 bb
	ON	aa.KODE_SATKER = bb.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) cc
	ON	substr(bb.kode_unit,1,3) = cc.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) dd
	ON	bb.kode_unit = dd.KODE;
create index SAKTIKSL.IDX_MV_KBBPN_221023_ba on SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023(kode_ba_satker);
create index SAKTIKSL.IDX_MV_KBBPN_221023_baES1 on SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023(kode_ba_satker||kode_eselon1_satker);
create index SAKTIKSL.IDX_MV_KBBPN_221023_AKT on SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023(JNS_AKTIFITAS);
create index SAKTIKSL.IDX_MV_KBBPN_221023_REFGL on SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023(NO_REF_GL);
create index SAKTIKSL.IDX_MV_KBBPN_221023_REF on SAKTIKSL.MV_KAS_BANK_BEN_PEN_220930_221023(NO_REFERENSI);