DROP MATERIALIZED VIEW SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023
AS
--Tabel mencatat transaksi kas tunai di bendahara pengeluaran
SELECT	AA.JENIS_AKTIFITAS,
		CASE	WHEN AA.JENIS_AKTIFITAS = '0' THEN 'SBS'
				WHEN AA.JENIS_AKTIFITAS = '1' THEN 'SETOR_KE_BANK'
				WHEN AA.JENIS_AKTIFITAS = '2' THEN 'TARIK_DARI_BANK'
				WHEN AA.JENIS_AKTIFITAS = '3' THEN 'CATAT_LS_BENDAHARA'
				WHEN AA.JENIS_AKTIFITAS = '4' THEN 'PEMBAYARAN_DANA_TITIPAN'
				WHEN AA.JENIS_AKTIFITAS = '5' THEN 'MIGRASI_DATA'
				WHEN AA.JENIS_AKTIFITAS = '6' THEN 'HIBAH_MASUK'
				WHEN AA.JENIS_AKTIFITAS = '7' THEN 'HIBAH_KELUAR'
			END AS UR_JENIS_AKTIFITAS,
		AA.DELETED,
		CASE	WHEN AA.DELETED = '0' THEN 'data aktif'
				WHEN AA.DELETED = '1' THEN 'data dihapus'
			END AS UR_DELETED,
		AA.JUMLAH,
		AA.KATEGORI_KAS,
		CASE	WHEN AA.KATEGORI_KAS IN ('231','237') THEN 'LS_Bendahara'
				WHEN AA.KATEGORI_KAS = '311' THEN 'UP'
				WHEN AA.KATEGORI_KAS = '314' THEN 'UPKP'
				WHEN AA.KATEGORI_KAS = '317' THEN 'GUP_KKP'
				WHEN AA.KATEGORI_KAS = '321' THEN 'TUP'
				WHEN AA.KATEGORI_KAS = '323' THEN 'TUP_KKP'
				WHEN AA.KATEGORI_KAS = '325' THEN 'TUPKP'
				WHEN AA.KATEGORI_KAS = '512' THEN 'HIBAH'
				WHEN AA.KATEGORI_KAS = '666' THEN 'Kas Lainnya'
				WHEN AA.KATEGORI_KAS = '777' THEN 'POTONGAN_PAJAK'
				WHEN AA.KATEGORI_KAS = '999' THEN 'PNBP UMUM'
			END AS UR_KATEGORI_KAS,
		AA.NO_REFERENSI,
		AA.NO_UANG_MUKA,
		substr(bb.kode_unit,1,3)		kode_ba_satker,
		trim(cc.deskripsi)				nama_ba_satker,
		substr(bb.kode_unit,-2)			kode_eselon1_satker,
		trim(dd.deskripsi)				nama_eselon1_satker,
		AA.KODE_SATKER,
		trim(bb.deskripsi)				nama_satker,
		AA.KODE_SUMBER_DANA,
		EE.DESKRIPSI					ur_SUMBER_DANA,
		AA.KODE_TAHUN_ANGGARAN,
		AA.TGL_TRANSAKSI,
		AA.URAIAN,
		AA.NO_REF_GL,
		AA.NO_REGISTER,
		AA.KODE_UNIT_TEKNIS,
		AA.KODE_UNIT_TEKNIS_ASAL
FROM	SAKTIKSL.BPK_KAS_TUNAI_BEN_PENG_220930_221023	AA
left join	SAKTIKSL.BPK_ADM_R_SATKER_220731 bb
	ON	aa.KODE_SATKER = bb.KODE
left join
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '1'
	) cc
	ON	substr(bb.kode_unit,1,3) = cc.KODE
LEFT JOIN
	(	SELECT	DISTINCT *
		FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
		WHERE	LEVEL_ = '2'
	) dd
	ON	bb.kode_unit = dd.KODE
LEFT JOIN	saktiksl.REF_SUMBER_DANA_2022 EE
	on	aa.KODE_SUMBER_DANA = EE.KODE;
create index SAKTIKSL.IDX_MV_KTBPG_221023_ba on SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023(kode_ba_satker);
create index SAKTIKSL.IDX_MV_KTBPG_221023_baES1 on SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023(kode_ba_satker||kode_eselon1_satker);
create index SAKTIKSL.IDX_MV_KTBPG_221023_AKT on SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023(JENIS_AKTIFITAS);
create index SAKTIKSL.IDX_MV_KTBPG_221023_REFGL on SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023(NO_REF_GL);
create index SAKTIKSL.IDX_MV_KTBPG_221023_REF on SAKTIKSL.MV_KAS_TUNAI_BEN_PENG_220930_221023(NO_REFERENSI);