/*
Table Required: 
	BPK_GLP_NRC_SAWAL_220731					--AVAILABLE / MAKE SURE COUNT DISTINCT KDPERK6 NOT > 1 (DONE)
	BPK_ADM_R_KEMENTERIAN_220731				--AVAILABLE / MAKE SURE COUNT DISTINCT KDBAES1 NOT > 1 (DONE)
	BPK_ADM_R_SATKER_220731						--AVALIABLE
	BPK_ADM_R_AKUN_220731						--AVALIABLE
*/
DROP MATERIALIZED VIEW SAKTIKSL.MV_GLP_NRC_SAWAL_220930_221023;
CREATE MATERIALIZED VIEW SAKTIKSL.MV_GLP_NRC_SAWAL_220930_221023 
as
select	SUBSTR(SAI.KDBAES1,1,3)	KODE_BA_SATKER,
		TRIM(BB.DESKRIPSI)		NAMA_BA_SATKER,
		SUBSTR(SAI.KDBAES1,-2)	KODE_ESELON1_SATKER,
		SAI.KDBAES1				KODE_BAES1_SATKER,
		TRIM(CC.DESKRIPSI)		NAMA_ESELON1_SATKER,
		SAI.KODE_SATKER,
		TRIM(DD.DESKRIPSI)		NAMA_SATKER,
		SAI.AKUN				KODE_AKUN,
		trim(EE.DESKRIPSI)		NAMA_AKUN,
		SAI.SALDO_AWAL
from SAKTIKSL.BPK_GLP_NRC_SAWAL_220731 sai
LEFT JOIN 
(	SELECT	DISTINCT *
	FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
	WHERE	LEVEL_ = '1'
) BB
	ON	SUBSTR(SAI.KDBAES1,1,3) = BB.KODE
LEFT JOIN
(	SELECT	DISTINCT *
	FROM	saktiksl.BPK_ADM_R_KEMENTERIAN_220731
	WHERE	LEVEL_ = '2'
) CC
	ON	SUBSTR(SAI.KDBAES1,1,3)||'.'||SUBSTR(SAI.KDBAES1,-2) = cc.kode
LEFT JOIN	SAKTIKSL.BPK_ADM_R_SATKER_220731	DD
	ON	SAI.KODE_SATKER = DD.KODE
LEFT JOIN	SAKTIKSL.BPK_ADM_R_AKUN_220731	EE
	ON	SAI.AKUN = EE.KODE;
CREATE INDEX SAKTIKSL.IDX_MGNS_221023_KDBA ON SAKTIKSL.MV_GLP_NRC_SAWAL_220930_221023 (KODE_BA_SATKER);
CREATE INDEX SAKTIKSL.IDX_MGNS_221023_AKN ON SAKTIKSL.MV_GLP_NRC_SAWAL_220930_221023 (KODE_BAES1_SATKER);
CREATE INDEX SAKTIKSL.IDX_MGNS_221023_TRN ON SAKTIKSL.MV_GLP_NRC_SAWAL_220930_221023 (KODE_AKUN);